### PR TITLE
step info handling improvements

### PR DESCRIPTION
**Pull request by RyanHope**
accumulate step info in arrays instead of summing values, pass last info to end of episode callbacks

### CODE REVIEW

**Comment by matthiasplappert** [comment]
Have you tested if that works the `TrainEpisodeLogger` (`verbose=1`)?

**Comment by RyanHope** [comment]
TrainEpisodeLogger doesn't have a verbose param ;) I did try verbose=1 and verbose=2 on the fit/train methods and didn't get any errors.

**Comment by matthiasplappert** [comment]
Alright. Can you clarify why this is needed? It seams reasonable to me to sum over the infos if `action_repetition` is > 1.

**Comment by RyanHope** [comment]
Now that I think I about it. Leaving the accumulated info as arrays is not needed any more now that I stick the final info into the log. I initially wanted the game info exposed as metrics and was going to move the summing to the loggers code that processed the metrics. None of that is needed if the info is just added to the info. I needed a way of getting end of episode stats into the logs. I will remove this change from the PR.

**Pull request closed without merging**
