### PR TITLE
Enabling dropout layers to be used in the actor and critic models.

### PR DESCRIPTION
**Pull request by ParthaEth**
The `K.learning_phase()` flag was not being passed correctly to `k.function()`, resulting in `AttributeError: 'Tensor' object has no attribute '_keras_shape' ` since the return value of `K.learning_phase()` was getting treated as normal input tensor to the model. This change fixes this. The reason for this is the segment `self.actor(critic_inputs)`. the actor should not receive `K.learning_phase()`

### CODE REVIEW

**Comment by ParthaEth** [comment]
Spotted some errors will open it if I can fix them.

**Comment by ParthaEth** [comment]
Hi @matthiasplappert can we put this through?

**Comment by matthiasplappert** [comment]
I see, makes sense. Why is the special case for Theano necessary though? Shouldn't the same argument equally apply to Theano?

**Comment by ParthaEth** [comment]
@matthiasplappert I don't really know. Some how Theano expects the learningPhase flag all the time. I was getting errors otherwise.

**Comment by matthiasplappert** [comment]
Alright, merging this since tests seem to be fine.

**Pull request merged**
