### PR TITLE
Fix default policy handling of DQNAgent

### PR DESCRIPTION
**Pull request by obsproth**

### CODE REVIEW

**Comment by matthiasplappert** [comment]
Why is this change necessary?

**Comment by obsproth** [comment]
Because multiple DQNAgents share one policy instance.
This may cause unexpected behaviors.
e.g.
```from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense
from rl.agents.dqn import DQNAgent
from rl.memory import SequentialMemory

nb_actions = 1

model1 = Sequential()
model1.add(Dense(nb_actions, input_dim=3))
model2 = Sequential()
model2.add(Dense(nb_actions, input_dim=3))

dqn1 = DQNAgent(model1, nb_actions=nb_actions, memory=SequentialMemory(limit=3,window_length=1))
dqn2 = DQNAgent(model2, nb_actions=nb_actions, memory=SequentialMemory(limit=3,window_length=1))
```
`eps` update affects others.
```
print(dqn2.policy.eps) #0.1
dqn1.policy.eps = 0.2
print(dqn2.policy.eps) #0.2
```
`policy.agent` will be overwritten.
```
print(dqn1.policy.agent == dqn2) #True
```

**Comment by matthiasplappert** [comment]
You are absolutely right. I always forget about this somewhat weird behvior. Thanks for the fix!

**Comment by raopku** [comment]
it is a strange phenomenon caused by python syntax
The default constructor will only be initialized once

class b(object):
    def __init__(self):
        print("init b object")

class a(object):
    def __init__(self, a=b()):
        self.object = a

dqn1 = a()
dqn2 = a()

print(id(dqn2.object))
print(id(dqn1.object))

result:
init b object
44977232
44977232

**Pull request merged**
