### PR TITLE
logging hotfix

### PR DESCRIPTION
**Pull request by bkj**
Copy callbacks array to resolve issue #12

### CODE REVIEW

**Comment by SimonRamstedt** [comment]
Hey, have you tested it? Because `callbacks = callbacks[:]` is doing nothing as far as I know.

**Comment by bkj** [comment]
It copies the array, right?

```
a = [1, 2, 3]
b = a
b[0] = 0
print a, b
# [0, 2, 3] [0, 2, 3]

# vs

a = [1, 2, 3]
b = a[:]
b[0] = 0

print a, b
# [1, 2, 3] [0, 2, 3]
```

**Comment by SimonRamstedt** [comment]
Yes I just thougth this shouldn't matter because its an empty list anyway but apparently this is a python quirk: http://effbot.org/zone/default-values.htm

**Comment by bkj** [comment]
Huh, that's a new one to me.

That seems like a better solution though -- I'll update and resubmit PR

**Pull request merged**
