### PR TITLE
Compatibility with Keras 2 (cdqn fixes)

### PR DESCRIPTION
**Pull request by bstriner**
Couldn't figure out why changes weren't working on keras2. I refactored NAFLayer to take 3 inputs instead of 1 concatenated input. No idea what broke it but this seems to fix it. Checking if this pr works on travis.

Branched from your keras2.

### CODE REVIEW

**Comment by bstriner** [comment]
Had to do some further refactoring to get it working in both backends. Removed the repeat and merge sum and used a Lambda instead. Also had to implement `compute_output_shape`.

I put in a compatibility module to remove warnings but let it still work on Keras 1. `rl.keras_future` has functions `add`, `concatenate` and `Model` which will use the 1 or 2 APIs as appropriate. Calls to `merge` or `model` could be changed to `rl.keras.future` functions.

**Comment by bstriner** [comment]
@matthiasplappert Wow! That was a pain but Travis is finally happy!

Note that the shape of merge layers is currently wonky in keras. I switched to a lambda layer with a custom output_shape so the shape will be the same in keras 1 and 2. See: https://github.com/fchollet/keras/issues/5784

Cheers

**Comment by bstriner** [comment]
Last changes pushed. Fixed the output shape. Still worked with the wrong shape but summary was wrong.

**Comment by matthiasplappert** [comment]
Wow, thanks a lot for taking care of this! All looks good, merging now.

**Pull request merged**
