### PR TITLE
Add correct dimensionality for the OUProcess

### PR DESCRIPTION
**Pull request by benelot**
This does not fix this very example but solves a problem as soon as somebody builds an example which has more than one dimension based on this one.

I was just about to write my own OUProcess based on your when I realized that it has the size parameter. Since my example is a cartpole moving in a plane (2 continuous actions), I needed 2D OrnsteinUhlenbeckNoise. Otherwise I received a failing assert noise.shape == action_space.shape. So maybe this saves somebody a quarter of an hour of searching for the problem.

### CODE REVIEW

**Comment by benelot** [comment]
I have no idea why this is failing here. The CI output looks a bit cryptic to me.

**Comment by kashif** [comment]
@benelot its probably because in my branch I updated keras and since the new version satisfies the requirement of your branch, travis does not install the older version of keras and thus gives the errors which I have fixed in my branch... hope that explains it.

**Comment by benelot** [comment]
I am running the changes I provided here on the newest version of Keras as well. And I made my changes directly from the page of github based on the newest version? So my changes should be applicable to the newest revision per definition. What do I have to do to get the changes merged?

**Comment by matthiasplappert** [comment]
Yeah, that's a lot cleaner. CI failed because of an unrelated change to keras, so all is good. Merging this now.

**Pull request merged**
